// ─────────────────────────────────────────────────────────────
// COMPREHENSIVE INGREDIENT KNOWLEDGE BASE (TASK 5 — XAI)
// 25+ ingredients with full profiles for explainability
// ─────────────────────────────────────────────────────────────

import type { IngredientInfo, HarmfulCombination } from '../types';

// ── Full Ingredient Profiles ──
export const ingredientDatabase: Record<string, IngredientInfo> = {
  'salicylic acid': {
    name: 'Salicylic Acid',
    alternativeNames: ['bha', 'beta hydroxy acid', 'salicylate', '2-hydroxybenzoic acid'],
    category: 'BHA (Beta Hydroxy Acid)',
    purpose: 'Oil-soluble exfoliant that penetrates deep into pores to dissolve sebum, dead skin cells, and debris — the #1 acne-fighting ingredient.',
    howItWorks: 'Salicylic acid is oil-soluble, unlike AHAs which are water-soluble. This allows it to penetrate through the lipid layers of the pore lining, dissolving the "glue" (desmosomes) between dead skin cells and breaking down trapped sebum. It directly targets the root cause of blackheads and whiteheads.',
    benefits: ['Clears clogged pores from inside out', 'Reduces blackheads and whiteheads', 'Controls excess oil production', 'Reduces inflammation in active acne', 'Prevents future breakouts', 'Improves skin texture'],
    sideEffects: ['Dryness and peeling at high concentrations', 'Mild stinging on sensitive skin', 'Increased sun sensitivity', 'Overuse can damage skin barrier', 'Initial purging period (2-6 weeks)'],
    bestFor: ['oily', 'combination', 'acne-prone', 'blackheads', 'enlarged pores'],
    avoidFor: ['very dry', 'sensitive', 'compromised barrier', 'rosacea'],
    usageTips: 'Start with 0.5-2% concentration. Use in PM. Apply after cleansing, before moisturizer. Do not combine with other strong acids on the same night.',
    strength: 'strong',
    comedogenicRating: 0,
  },
  'glycolic acid': {
    name: 'Glycolic Acid',
    alternativeNames: ['aha', 'alpha hydroxy acid', 'hydroxyacetic acid'],
    category: 'AHA (Alpha Hydroxy Acid)',
    purpose: 'The smallest AHA molecule — deeply exfoliates the skin surface to reveal brighter, smoother, more even-toned skin.',
    howItWorks: 'Glycolic acid has the smallest molecular size of all AHAs, allowing it to penetrate the skin effectively. It works by breaking the bonds (desmosomes) between dead skin cells on the surface, causing them to shed naturally. This accelerates cell turnover, revealing fresh skin underneath and stimulating collagen production.',
    benefits: ['Brightens dull complexion', 'Reduces hyperpigmentation and dark spots', 'Smooths fine lines and wrinkles', 'Improves skin texture and radiance', 'Stimulates collagen production', 'Enhances product absorption'],
    sideEffects: ['Sun sensitivity increases significantly', 'Stinging or burning sensation', 'Redness and irritation', 'Over-exfoliation damages barrier', 'Dryness and flaking', 'Not safe during pregnancy at high %'],
    bestFor: ['oily', 'combination', 'aging', 'dull skin', 'pigmentation', 'uneven texture'],
    avoidFor: ['sensitive', 'very dry', 'rosacea', 'eczema', 'sunburned skin'],
    usageTips: 'Start with 5-7% concentration, 1-2x per week. Always follow with SPF 30+ in the morning. Never use with retinol on the same night.',
    strength: 'strong',
    comedogenicRating: 0,
  },
  'retinol': {
    name: 'Retinol',
    alternativeNames: ['vitamin a', 'retinoid', 'retinal', 'retinaldehyde', 'retinyl palmitate'],
    category: 'Retinoid (Vitamin A Derivative)',
    purpose: 'The gold standard anti-aging ingredient — accelerates cell turnover, boosts collagen, and treats acne by preventing clogged pores.',
    howItWorks: 'Retinol penetrates the skin and converts to retinoic acid (the active form). It binds to retinoid receptors in skin cells, accelerating cell turnover from ~28 days to ~14 days. It stimulates collagen and elastin production, unclogs pores, and reduces melanin production. This multi-pathway action makes it effective for aging, acne, and pigmentation simultaneously.',
    benefits: ['Reduces fine lines and wrinkles', 'Prevents and treats acne', 'Fades dark spots and hyperpigmentation', 'Improves skin texture and firmness', 'Boosts collagen production', 'Minimizes pore appearance'],
    sideEffects: ['Redness and irritation (retinization)', 'Dryness and peeling (especially first 2-4 weeks)', 'Increased sun sensitivity', 'Not safe during pregnancy', 'Purging period (temporary worsening)', 'Can cause burning if mixed with wrong products'],
    bestFor: ['oily', 'combination', 'aging', 'acne-prone', 'pigmentation'],
    avoidFor: ['sensitive', 'rosacea', 'eczema', 'pregnant/breastfeeding', 'compromised barrier'],
    usageTips: 'Start with 0.25-0.3% concentration, 2-3x per week. Apply in PM only. Use after cleansing, before moisturizer ("sandwich method" for sensitive skin). Always pair with SPF. Do NOT combine with Vitamin C, AHAs, or BHAs on the same night.',
    strength: 'strong',
    comedogenicRating: 0,
  },
  'niacinamide': {
    name: 'Niacinamide',
    alternativeNames: ['vitamin b3', 'nicotinamide', 'niacin'],
    category: 'Vitamin B3',
    purpose: 'The Swiss Army knife of skincare — controls oil, minimizes pores, reduces redness, strengthens barrier, and brightens skin tone.',
    howItWorks: 'Niacinamide is a water-soluble vitamin that works on multiple skin pathways simultaneously. It inhibits melanosome transfer (reducing hyperpigmentation), regulates sebum production, boosts ceramide synthesis (strengthening barrier), reduces inflammation by blocking inflammatory cytokines, and improves skin elasticity by increasing collagen production.',
    benefits: ['Controls oil production by up to 23%', 'Minimizes pore appearance', 'Reduces redness and inflammation', 'Strengthens skin barrier (boosts ceramides)', 'Fades dark spots and hyperpigmentation', 'Reduces fine lines', 'Compatible with almost all ingredients'],
    sideEffects: ['Very rare — one of the most well-tolerated actives', 'High concentrations (>10%) may cause mild flushing', 'Very rarely, allergic contact dermatitis'],
    bestFor: ['oily', 'dry', 'combination', 'sensitive', 'acne-prone', 'aging', 'pigmentation', 'rosacea'],
    avoidFor: [],
    usageTips: 'Safe for AM and PM use. Works well at 2-5% concentration. Can be layered with most ingredients. Particularly effective alongside zinc, hyaluronic acid, and ceramides.',
    strength: 'gentle',
    comedogenicRating: 0,
  },
  'hyaluronic acid': {
    name: 'Hyaluronic Acid',
    alternativeNames: ['ha', 'sodium hyaluronate', 'hyaluronan'],
    category: 'Humectant',
    purpose: 'A moisture-binding molecule that holds 1000x its weight in water — the ultimate hydration ingredient for plump, dewy skin.',
    howItWorks: 'Hyaluronic acid is a glycosaminoglycan naturally found in skin. It acts as a "water magnet," attracting and holding moisture from the environment and deeper skin layers. One HA molecule can hold up to 1000 water molecules. Multiple molecular weights penetrate different skin depths: low MW goes deeper, high MW stays on surface for instant plumping.',
    benefits: ['Intensely hydrates without feeling heavy', 'Plumps fine lines from within', 'Supports wound healing', 'Strengthens skin barrier', 'Suitable for ALL skin types', 'Layer well under all products'],
    sideEffects: ['In dry climates, can pull moisture FROM skin if not sealed with moisturizer', 'Rarely causes irritation', 'Over-hydration can weaken barrier'],
    bestFor: ['oily', 'dry', 'combination', 'sensitive', 'aging', 'dehydrated', 'all skin types'],
    avoidFor: [],
    usageTips: 'Apply to DAMP skin after cleansing. Follow with a moisturizer to "seal in" the hydration. Use both AM and PM. Look for products with multiple molecular weights (multi-weight HA) for best results.',
    strength: 'gentle',
    comedogenicRating: 0,
  },
  'vitamin c': {
    name: 'Vitamin C',
    alternativeNames: ['l-ascorbic acid', 'ascorbic acid', 'sodium ascorbyl phosphate', 'magnesium ascorbyl phosphate', 'ascorbyl glucoside', 'tetrahexyldecyl ascorbate'],
    category: 'Antioxidant (Vitamin C)',
    purpose: 'The most powerful antioxidant in skincare — brightens skin, fades dark spots, boosts collagen, and shields against UV/environmental damage.',
    howItWorks: 'Vitamin C (L-ascorbic acid) works by inhibiting tyrosinase (the enzyme that produces melanin), directly reducing hyperpigmentation. It also serves as an essential cofactor for collagen synthesis — without it, collagen production slows. As an antioxidant, it neutralizes free radicals from UV exposure and pollution before they can damage skin cells.',
    benefits: ['Brightens complexion significantly', 'Fades dark spots and melasma', 'Boosts collagen production', 'Protects against UV damage (works synergistically with SPF)', 'Reduces inflammation', 'Improves skin firmness'],
    sideEffects: ['Oxidizes quickly — turns yellow/brown', 'Can cause stinging on sensitive skin', 'L-ascorbic acid is unstable in light/air', 'High concentrations (>20%) can irritate', 'Low pH requirement may cause sensitivity'],
    bestFor: ['oily', 'dry', 'combination', 'aging', 'dull skin', 'pigmentation', 'sun damage'],
    avoidFor: ['very sensitive (use gentler derivatives)'],
    usageTips: 'Use L-ascorbic acid at 10-20% in AM. Apply after cleansing, before SPF. Store in opaque, airtight container. Discard if it turns dark yellow/brown (oxidized). SAP and MAP derivatives are gentler alternatives.',
    strength: 'moderate',
    comedogenicRating: 0,
  },
  'benzoyl peroxide': {
    name: 'Benzoyl Peroxide',
    alternativeNames: ['bp', 'benzoperoxide', 'dibenzoyl peroxide'],
    category: 'Antibacterial / Antimicrobial',
    purpose: 'The most effective OTC acne-fighting ingredient — kills acne-causing bacteria (C. acnes) on contact and reduces inflammation.',
    howItWorks: 'Benzoyl peroxide releases free radical oxygen into the pore, which creates an environment where Cutibacterium acnes (the acne-causing bacteria) cannot survive. Unlike antibiotics, bacteria cannot develop resistance to BP. It also has mild keratolytic (exfoliating) action that helps unclog pores.',
    benefits: ['Kills 99.9% of acne-causing bacteria', 'No bacterial resistance possible', 'Reduces inflammatory acne quickly', 'Unclogs pores', 'Reduces excess oil', 'Works within 4-6 weeks'],
    sideEffects: ['Significant dryness and peeling', 'Redness and burning sensation', 'Bleaches fabrics (towels, pillowcases)', 'Can cause contact dermatitis', 'Increases sun sensitivity', 'Not for sensitive skin'],
    bestFor: ['oily', 'acne-prone', 'inflammatory acne'],
    avoidFor: ['sensitive', 'dry', 'rosacea', 'eczema', 'pregnant (category C)'],
    usageTips: 'Start with 2.5% (equally effective as 10% with less irritation). Apply as a spot treatment or thin layer. Use in PM. Keep away from eyebrows and hair (bleaching effect). Moisturize well after.',
    strength: 'strong',
    comedogenicRating: 0,
  },
  'ceramides': {
    name: 'Ceramides',
    alternativeNames: ['ceramide np', 'ceramide ap', 'ceramide eop', 'phytosphingosine', 'sphingolipids'],
    category: 'Barrier Repair (Lipid)',
    purpose: 'The "mortar" between skin cells — makes up 50% of your skin barrier. Essential for repairing damaged skin and preventing moisture loss.',
    howItWorks: 'Ceramides are lipids (fats) naturally found in the stratum corneum (outermost skin layer). They form a waterproof barrier between skin cells (corneocytes), preventing transepidermal water loss (TEWL) and blocking irritants/pathogens from entering. When skin is damaged, ceramide levels drop by up to 50%, leading to dryness, sensitivity, and acne.',
    benefits: ['Repairs damaged skin barrier', 'Prevents moisture loss (reduces TEWL)', 'Protects against environmental irritants', 'Reduces sensitivity and reactivity', 'Helps eczema and rosacea', 'Anti-aging (firming effect)'],
    sideEffects: ['Extremely rare — ceramides are naturally present in skin', 'No known side effects for any skin type'],
    bestFor: ['oily', 'dry', 'combination', 'sensitive', 'aging', 'eczema', 'rosacea', 'damaged barrier', 'all skin types'],
    avoidFor: [],
    usageTips: 'Apply after cleansing and serums. Look for products with multiple ceramide types (NP, AP, EOP) + cholesterol + fatty acids for optimal barrier repair. Use both AM and PM.',
    strength: 'gentle',
    comedogenicRating: 0,
  },
  'azelaic acid': {
    name: 'Azelaic Acid',
    alternativeNames: ['dicarboxylic acid', 'azelex', 'finacea'],
    category: 'Dicarboxylic Acid',
    purpose: 'A multi-tasking ingredient that fights acne, reduces redness, fades pigmentation, and fights rosacea — all while being pregnancy-safe.',
    howItWorks: 'Azelaic acid is a naturally occurring dicarboxylic acid produced by Malassezia furfur (a yeast on skin). It works by inhibiting tyrosinase (reducing pigmentation), reducing keratin production (preventing clogged pores), and has direct antimicrobial and anti-inflammatory effects against C. acnes. It is FDA-approved for rosacea treatment.',
    benefits: ['Treats acne and prevents new breakouts', 'Reduces redness and rosacea symptoms', 'Fades post-inflammatory hyperpigmentation (PIH)', 'Safe during pregnancy', 'Reduces skin sensitivity over time', 'Anti-inflammatory without harshness'],
    sideEffects: ['Mild tingling or burning initially', 'Dryness at higher concentrations', 'Can cause itchiness', 'Prescription strength (15%) may cause more irritation'],
    bestFor: ['oily', 'combination', 'sensitive', 'acne-prone', 'rosacea', 'pigmentation', 'pregnant'],
    avoidFor: [],
    usageTips: 'Use 10% OTC or 15% prescription. Apply in PM after cleansing. Safe to combine with niacinamide. Can be used AM and PM — start with PM only.',
    strength: 'mild',
    comedogenicRating: 0,
  },
  'zinc': {
    name: 'Zinc',
    alternativeNames: ['zinc oxide', 'zinc pca', 'zinc gluconate', 'zinc sulfate'],
    category: 'Mineral',
    purpose: 'A natural oil-controller and anti-inflammatory mineral that regulates sebum, fights acne-causing bacteria, and provides sun protection.',
    howItWorks: 'Zinc is an essential mineral that modulates sebaceous gland activity, reducing sebum output. It has direct antibacterial effects against C. acnes, reduces inflammatory cytokines (IL-6, TNF-α), and promotes wound healing. Zinc oxide sits on the skin surface and reflects/absorbs UV radiation, making it a physical sunscreen active.',
    benefits: ['Controls oil production', 'Reduces acne inflammation', 'Promotes wound healing', 'Natural UV protection (zinc oxide)', 'Anti-inflammatory', 'Safe for sensitive skin'],
    sideEffects: ['Very rare topically', 'Zinc oxide can leave white cast', 'Oral zinc can cause nausea (not relevant topically)'],
    bestFor: ['oily', 'combination', 'sensitive', 'acne-prone', 'all skin types'],
    avoidFor: [],
    usageTips: 'Look for zinc PCA in serums for oil control. Zinc oxide in sunscreens provides broad-spectrum UV protection. Niacinamide + zinc is an excellent oil-control combo.',
    strength: 'gentle',
    comedogenicRating: 0,
  },
  'tea tree oil': {
    name: 'Tea Tree Oil',
    alternativeNames: ['melaleuca alternifolia', 'melaleuca oil', 'ti tree oil'],
    category: 'Essential Oil / Antimicrobial',
    purpose: 'A natural antimicrobial essential oil — proven as effective as 5% benzoyl peroxide for acne but with fewer side effects.',
    howItWorks: 'Tea tree oil contains terpinen-4-ol, its primary active compound, which disrupts the cell membranes of C. acnes bacteria. It also modulates the immune system\'s inflammatory response, reducing redness and swelling. Clinical studies show 5% TTO gel is comparable to 5% BP for mild-to-moderate acne.',
    benefits: ['Fights acne-causing bacteria naturally', 'Reduces inflammation', 'Less irritating than benzoyl peroxide', 'Controls oil', 'Antifungal properties'],
    sideEffects: ['Can cause allergic contact dermatitis', 'MUST be diluted (never apply 100%)', 'Can be drying', 'Not safe for pets (toxic if ingested)', 'Strong scent'],
    bestFor: ['oily', 'combination', 'mild acne'],
    avoidFor: ['sensitive', 'very dry', 'eczema', 'allergy-prone'],
    usageTips: 'NEVER apply undiluted. Use products with 5% TTO concentration. Dilute pure TTO with carrier oil (jojoba) at 1:9 ratio. Patch test first.',
    strength: 'moderate',
    comedogenicRating: 0,
  },
  'centella asiatica': {
    name: 'Centella Asiatica',
    alternativeNames: ['cica', 'gotu kola', 'tiger grass', 'madecassoside', 'asiaticoside', 'madecassic acid'],
    category: 'Botanical / Skin Repair',
    purpose: 'A legendary wound-healing botanical — stimulates collagen synthesis, repairs damaged skin, and calms inflammation.',
    howItWorks: 'Centella asiatica contains triterpenoids (asiaticoside, madecassoside, asiatic acid, madecassic acid) that stimulate fibroblast proliferation and collagen synthesis. It increases type I and III collagen, the two most important structural proteins. It also modulates inflammation by inhibiting NF-κB pathway.',
    benefits: ['Accelerates wound healing', 'Stimulates collagen production', 'Calms redness and inflammation', 'Repairs damaged skin barrier', 'Anti-aging (firming effect)', 'Safe for all skin types'],
    sideEffects: ['Very rare', 'Extremely well-tolerated', 'Occasional mild allergic reaction'],
    bestFor: ['oily', 'dry', 'combination', 'sensitive', 'acne-prone', 'damaged barrier', 'all skin types'],
    avoidFor: [],
    usageTips: 'Look for "Cica" products. Apply AM and PM. Works excellently with ceramides and panthenol for barrier repair. Madecassoside is the most potent compound.',
    strength: 'gentle',
    comedogenicRating: 0,
  },
  'squalane': {
    name: 'Squalane',
    alternativeNames: ['squalene', 'olive squalane', 'plant-derived squalane'],
    category: 'Emollient / Moisturizer',
    purpose: 'A lightweight, non-comedogenic oil that mimics your skin\'s natural sebum — hydrates without clogging pores.',
    howItWorks: 'Squalane is the hydrogenated (stable) form of squalene, a lipid naturally produced by your sebaceous glands that makes up ~13% of sebum. Because it is bioidentical to your skin\'s own oils, it absorbs instantly without greasiness. It forms a lightweight occlusive layer that prevents moisture loss while allowing skin to breathe.',
    benefits: ['Deep hydration without greasiness', 'Non-comedogenic (will not clog pores)', 'Strengthens skin barrier', 'Lightweight — suitable even for oily skin', 'Anti-oxidant properties', 'Reduces fine lines by improving elasticity'],
    sideEffects: ['Extremely rare', 'One of the safest moisturizing ingredients', 'Plant-derived versions are non-irritating'],
    bestFor: ['oily', 'dry', 'combination', 'sensitive', 'acne-prone', 'all skin types'],
    avoidFor: [],
    usageTips: 'Apply 2-3 drops after serums, before or mixed with moisturizer. Works for both AM and PM. Excellent as a standalone moisturizer for oily skin.',
    strength: 'gentle',
    comedogenicRating: 0,
  },
  'peptides': {
    name: 'Peptides',
    alternativeNames: ['matrixyl', 'argireline', 'copper peptides', 'signal peptides', 'palmitoyl pentapeptide', 'hexapeptide', 'tripeptide'],
    category: 'Protein / Anti-Aging',
    purpose: 'Amino acid chains that signal your skin to produce more collagen, elastin, and other structural proteins — the building blocks of youthful skin.',
    howItWorks: 'Peptides are short chains of amino acids that act as cellular messengers. Signal peptides (like Matrixyl) tell fibroblasts to produce more collagen. Neurotransmitter-inhibiting peptides (like Argireline) reduce muscle contractions (botox-like effect). Copper peptides promote wound healing and antioxidant defense.',
    benefits: ['Stimulates collagen production', 'Reduces wrinkle depth and number', 'Improves skin firmness and elasticity', 'Accelerates wound healing', 'Anti-inflammatory properties', 'Safe for all skin types'],
    sideEffects: ['Very rare', 'Generally well-tolerated', 'Copper peptides may cause irritation in some'],
    bestFor: ['oily', 'dry', 'combination', 'sensitive', 'aging', 'all skin types'],
    avoidFor: [],
    usageTips: 'Apply in both AM and PM. Works well with hyaluronic acid, ceramides, and niacinamide. Do NOT mix with strong AHAs (low pH can degrade peptides). Results take 8-12 weeks.',
    strength: 'gentle',
    comedogenicRating: 0,
  },
  'aloe vera': {
    name: 'Aloe Vera',
    alternativeNames: ['aloe barbadensis', 'aloe gel', 'aloe extract'],
    category: 'Botanical / Soothing',
    purpose: 'A natural soothing and hydrating gel — calms sunburn, reduces inflammation, and provides lightweight hydration.',
    howItWorks: 'Aloe vera gel contains 75+ active compounds including polysaccharides (acemannan), vitamins (A, C, E, B12), minerals, amino acids, and enzymes. The polysaccharides form a protective, hydrating film on skin while stimulating macrophage activity for wound healing. Glycoproteins reduce inflammation and pain.',
    benefits: ['Soothes sunburn and irritation', 'Lightweight hydration', 'Anti-inflammatory', 'Wound healing', 'Antioxidant protection', 'Safe for all skin types including sensitive'],
    sideEffects: ['Very rare', 'Generally recognized as safe', 'Occasional allergic reactions'],
    bestFor: ['oily', 'dry', 'combination', 'sensitive', 'sunburned', 'all skin types'],
    avoidFor: [],
    usageTips: 'Use pure aloe gel or products with high aloe content. Apply after cleansing. Excellent as a soothing step after acid treatments or sun exposure.',
    strength: 'gentle',
    comedogenicRating: 0,
  },
  'panthenol': {
    name: 'Panthenol',
    alternativeNames: ['vitamin b5', 'provitamin b5', 'dexpanthenol', 'pantothenic acid'],
    category: 'Vitamin B5',
    purpose: 'A deeply hydrating and healing vitamin — attracts moisture, repairs damaged skin, and reduces inflammation.',
    howItWorks: 'Panthenol (provitamin B5) converts to pantothenic acid in the skin. It functions as a humectant (attracting water), improves skin barrier function by increasing lipid synthesis, and accelerates wound healing by stimulating fibroblast proliferation. It also reduces inflammation by modulating inflammatory mediators.',
    benefits: ['Deep hydration (humectant)', 'Accelerates wound healing', 'Reduces inflammation and redness', 'Strengthens skin barrier', 'Soothes irritated skin', 'Safe for all skin types'],
    sideEffects: ['Extremely rare', 'One of the safest skincare ingredients'],
    bestFor: ['oily', 'dry', 'combination', 'sensitive', 'damaged barrier', 'all skin types'],
    avoidFor: [],
    usageTips: 'Found in many moisturizers and serums. Apply after cleansing. Works synergistically with ceramides and niacinamide for barrier repair.',
    strength: 'gentle',
    comedogenicRating: 0,
  },
  'lactic acid': {
    name: 'Lactic Acid',
    alternativeNames: ['alpha hydroxy acid', '2-hydroxypropanoic acid', 'milk acid'],
    category: 'AHA (Alpha Hydroxy Acid)',
    purpose: 'A gentler AHA that exfoliates while simultaneously hydrating — perfect for sensitive skin that needs brightening without irritation.',
    howItWorks: 'Lactic acid is an AHA derived from milk (or synthetically produced). Like glycolic acid, it breaks bonds between dead skin cells. However, its larger molecular size means slower penetration and gentler exfoliation. Uniquely, it also acts as a humectant, attracting moisture to the skin — the only AHA that hydrates while exfoliating.',
    benefits: ['Gentle exfoliation suitable for sensitive skin', 'Brightens complexion', 'Hydrates while exfoliating', 'Reduces hyperpigmentation', 'Improves skin texture', 'Stimulates collagen production'],
    sideEffects: ['Mild stinging', 'Sun sensitivity', 'Less irritation than glycolic acid', 'Overuse can cause barrier damage'],
    bestFor: ['dry', 'combination', 'sensitive', 'aging', 'dull skin', 'beginners to AHAs'],
    avoidFor: ['compromised barrier', 'active rosacea'],
    usageTips: 'Start with 2-5%, 1-2x per week. Use in PM. The gentlest AHA — perfect for beginners. Always follow with SPF.',
    strength: 'mild',
    comedogenicRating: 0,
  },
  'mandelic acid': {
    name: 'Mandelic Acid',
    alternativeNames: ['amygdalic acid', 'phenylglycolic acid', 'alpha hydroxy acid'],
    category: 'AHA (Alpha Hydroxy Acid)',
    purpose: 'The largest AHA molecule — provides ultra-gentle exfoliation with antibacterial properties, ideal for sensitive and darker skin tones.',
    howItWorks: 'Mandelic acid is derived from bitter almonds. Its large molecular size means very slow, surface-level penetration, making it the gentlest AHA. It has natural antibacterial properties against C. acnes and regulates sebum production. It is particularly recommended for darker skin tones because it reduces hyperpigmentation with minimal inflammation.',
    benefits: ['Ultra-gentle exfoliation', 'Antibacterial against acne bacteria', 'Fades hyperpigmentation safely', 'Regulates sebum production', 'Safe for darker skin tones', 'Minimal irritation'],
    sideEffects: ['Very mild irritation compared to other AHAs', 'Sun sensitivity', 'Rare allergic reaction to almond-derived versions'],
    bestFor: ['sensitive', 'oily', 'combination', 'acne-prone', 'pigmentation', 'all skin tones'],
    avoidFor: ['nut allergy (almond-derived)'],
    usageTips: 'Use 5-10%, 2-3x per week. Safe to combine with other gentle actives. Particularly effective for acne + pigmentation concerns.',
    strength: 'mild',
    comedogenicRating: 0,
  },
  'ferulic acid': {
    name: 'Ferulic Acid',
    alternativeNames: ['ferulate', '4-hydroxy-3-methoxycinnamic acid'],
    category: 'Antioxidant',
    purpose: 'A powerful antioxidant that doubles the effectiveness of Vitamins C and E — the ultimate antioxidant booster.',
    howItWorks: 'Ferulic acid is a hydroxycinnamic acid found in plant cell walls. It neutralizes free radicals (reactive oxygen species) before they can damage skin cells and collagen. Critically, it stabilizes Vitamin C and E, preventing their oxidation and doubling their photoprotective effect when used together. The C + E + Ferulic combo is the gold standard antioxidant serum formulation.',
    benefits: ['Stabilizes Vitamin C and E', 'Doubles UV protection when combined with C+E', 'Neutralizes free radicals', 'Anti-aging', 'Anti-inflammatory', 'Reduces sun damage'],
    sideEffects: ['Very rare', 'Extremely well-tolerated', 'Some tingling possible'],
    bestFor: ['oily', 'dry', 'combination', 'sensitive', 'aging', 'all skin types'],
    avoidFor: [],
    usageTips: 'Use in AM with Vitamin C and E for maximum photoprotection. The classic CE Ferulic formula: 15% Vitamin C + 1% Vitamin E + 0.5% Ferulic Acid.',
    strength: 'gentle',
    comedogenicRating: 0,
  },
  'green tea': {
    name: 'Green Tea Extract',
    alternativeNames: ['camellia sinensis', 'egcg', 'epigallocatechin gallate', 'green tea polyphenols'],
    category: 'Botanical / Antioxidant',
    purpose: 'A potent polyphenol-rich antioxidant — fights free radicals, reduces inflammation, controls oil, and protects against UV damage.',
    howItWorks: 'Green tea contains catechins, particularly EGCG (epigallocatechin gallate), which is 25-100x more potent than Vitamins C and E as an antioxidant. EGCG inhibits sebum production by modulating sebaceous gland activity, reduces inflammation by blocking NF-κB, and provides DNA protection against UV-induced damage.',
    benefits: ['Powerful antioxidant protection', 'Controls oil production', 'Anti-inflammatory', 'Protects against UV damage', 'Reduces acne', 'Anti-aging'],
    sideEffects: ['Very rare', 'Extremely well-tolerated', 'Some may be sensitive to caffeine content'],
    bestFor: ['oily', 'combination', 'sensitive', 'acne-prone', 'aging', 'all skin types'],
    avoidFor: [],
    usageTips: 'Use in toners, serums, or essences. Apply AM and PM. Works synergistically with other antioxidants (Vitamin C, ferulic acid).',
    strength: 'gentle',
    comedogenicRating: 0,
  },
  'snail mucin': {
    name: 'Snail Mucin',
    alternativeNames: ['snail secretion filtrate', 'snail slime', 'cosmetics snail', 'mucin'],
    category: 'Natural / Multi-Functional',
    purpose: 'A remarkable natural secretion — hydrates, repairs, soothes, and anti-ages all at once with zero irritation.',
    howItWorks: 'Snail mucin contains a complex mixture of hyaluronic acid, glycoproteins, proteoglycans, antimicrobial peptides, and copper peptides. These compounds work synergistically to hydrate (HA), repair (glycoproteins stimulate collagen), soothe (antimicrobial peptides reduce inflammation), and protect (copper peptides provide antioxidant defense).',
    benefits: ['Multi-depth hydration', 'Stimulates collagen and elastin production', 'Accelerates wound healing', 'Soothes irritation and redness', 'Improves skin texture', 'Safe for all skin types'],
    sideEffects: ['Very rare', 'Well-tolerated by all skin types', 'Ethical concerns (cruelty-free harvesting available)'],
    bestFor: ['oily', 'dry', 'combination', 'sensitive', 'aging', 'acne-prone', 'all skin types'],
    avoidFor: ['snail allergy (extremely rare)'],
    usageTips: 'Apply after cleansing, before heavier serums. Use both AM and PM. Look for 90%+ snail mucin concentration. No known ingredient conflicts.',
    strength: 'gentle',
    comedogenicRating: 0,
  },
  'rosehip oil': {
    name: 'Rosehip Oil',
    alternativeNames: ['rosa canina', 'rosehip seed oil', 'rosa rubiginosa'],
    category: 'Oil / Vitamin-Rich',
    purpose: 'A vitamin-rich facial oil packed with Vitamins A, C, and E — fades scars, brightens skin, and provides deep nourishment.',
    howItWorks: 'Rosehip oil is rich in trans-retinoic acid (a natural retinoid), vitamin C, vitamin E, essential fatty acids (linoleic acid ~50%, alpha-linolenic acid), and antioxidants. The trans-retinoic acid provides gentle retinoid benefits without prescription irritation. Linoleic acid is particularly beneficial because acne-prone skin has been shown to be deficient in this fatty acid.',
    benefits: ['Fades acne scars and hyperpigmentation', 'Rich in natural Vitamin A (gentle retinoid effect)', 'Brightens complexion', 'Deeply nourishes without heaviness', 'Anti-aging', 'Improves skin elasticity'],
    sideEffects: ['Can be heavy for very oily skin', 'May cause breakouts if comedogenic for individual', 'Cold-pressed quality varies'],
    bestFor: ['dry', 'combination', 'sensitive', 'aging', 'scarring', 'pigmentation'],
    avoidFor: ['very oily', 'cystic acne'],
    usageTips: 'Apply 2-3 drops as last step in PM routine. Cold-pressed, unrefined is best quality. Can replace PM moisturizer for dry skin types.',
    strength: 'gentle',
    comedogenicRating: 1,
  },
  'jojoba oil': {
    name: 'Jojoba Oil',
    alternativeNames: ['simmondsia chinensis', 'jojoba wax', 'jojoba ester'],
    category: 'Oil / Barrier Repair',
    purpose: 'A biomimetic oil that perfectly mimics human sebum — tricks your skin into producing less oil while deeply moisturizing.',
    howItWorks: 'Jojoba oil is technically a liquid wax ester, not an oil. Its molecular structure is remarkably similar to human sebum. When applied, it signals to sebaceous glands that sufficient oil is present, actually reducing sebum production. This "biomimetic" quality makes it the most skin-compatible oil available.',
    benefits: ['Mimics natural sebum perfectly', 'Regulates oil production (tricks skin)', 'Non-comedogenic', 'Deeply moisturizes', 'Rich in Vitamin E and B', 'Anti-inflammatory'],
    sideEffects: ['Extremely rare', 'One of the safest oils for all skin types'],
    bestFor: ['oily', 'dry', 'combination', 'sensitive', 'acne-prone', 'all skin types'],
    avoidFor: [],
    usageTips: 'Apply 2-4 drops after cleansing and serums. Excellent as a cleansing oil. Mix 1 drop with foundation for dewy finish. Safe for AM and PM.',
    strength: 'gentle',
    comedogenicRating: 2,
  },
  'witch hazel': {
    name: 'Witch Hazel',
    alternativeNames: ['hamamelis virginiana', 'witchhazel', 'hamamelis water'],
    category: 'Astringent / Toner',
    purpose: 'A natural astringent that tightens pores and controls oil — but alcohol-based versions can damage the skin barrier.',
    howItWorks: 'Witch hazel contains tannins (galloylated catechins, hamamelitannin) that have astringent properties — they cause protein coagulation in skin cells, temporarily tightening pores. It also has anti-inflammatory effects from flavonoids. However, many commercial witch hazel products contain denatured alcohol (15-30%), which is the real cause of dryness and barrier damage.',
    benefits: ['Temporarily tightens pores', 'Controls excess oil', 'Reduces inflammation', 'Soothes minor skin irritation', 'Natural antioxidant'],
    sideEffects: ['Alcohol-based versions damage barrier', 'Can be very drying', 'May cause irritation for sensitive skin', 'Tannins can be sensitizing long-term'],
    bestFor: ['oily', 'combination'],
    avoidFor: ['dry', 'sensitive', 'eczema', 'rosacea', 'damaged barrier'],
    usageTips: 'Choose ALCOHOL-FREE witch hazel only. Use as a toner after cleansing, 1x per day maximum. Discontinue if dryness occurs.',
    strength: 'moderate',
    comedogenicRating: 0,
  },
  'clay': {
    name: 'Clay',
    alternativeNames: ['kaolin', 'bentonite', 'french green clay', 'rhassoul clay', 'clay mask'],
    category: 'Absorbent / Detox',
    purpose: 'A natural absorbent that draws out impurities, excess oil, and toxins from pores — the original deep-cleansing treatment.',
    howItWorks: 'Clay minerals have a negative electrical charge that attracts positively charged toxins, heavy metals, and impurities. Kaolin clay is gentler (ideal for normal/dry), while bentonite clay is highly absorbent (ideal for oily/acne). When applied as a mask, clay absorbs excess sebum, draws out pore-clogging debris, and provides gentle physical exfoliation when removed.',
    benefits: ['Absorbs excess oil and sebum', 'Draws out impurities from pores', 'Reduces pore appearance', 'Gentle exfoliation', 'Detoxifies skin', 'Improves circulation'],
    sideEffects: ['Can be very drying if left on too long', 'May cause tightness', 'Not for daily use', 'Can irritate sensitive skin if overused'],
    bestFor: ['oily', 'combination', 'acne-prone', 'enlarged pores'],
    avoidFor: ['dry', 'sensitive', 'dehydrated skin'],
    usageTips: 'Use as a mask 1-2x per week. Apply to clean skin, leave on 10-15 minutes (don\'t let it fully dry/crack). Remove with lukewarm water. Follow with hydrating moisturizer.',
    strength: 'moderate',
    comedogenicRating: 0,
  },
};

// ── Harmful Ingredient Combinations (Task 5 specific) ──
export const harmfulCombinations: HarmfulCombination[] = [
  {
    ingredient1: 'retinol',
    ingredient2: 'vitamin c',
    severity: 'high',
    reason: 'Retinol and Vitamin C have incompatible pH requirements (Retinol needs pH 5.5-6.0, Vitamin C needs pH <3.5). Layering them causes irritation, reduces the effectiveness of both, and can cause oxidative damage.',
    suggestion: 'Use Vitamin C in AM (antioxidant + UV protection) and Retinol in PM (cell turnover + repair). Apply at least 12 hours apart.'
  },
  {
    ingredient1: 'retinol',
    ingredient2: 'glycolic acid',
    severity: 'high',
    reason: 'Retinol + AHA causes severe over-exfoliation. Both accelerate cell turnover, leading to destroyed skin barrier, severe redness, peeling, and inflammation. This combination is one of the most damaging possible.',
    suggestion: 'Alternate nights: Glycolic Acid on Monday/Wednesday, Retinol on Tuesday/Thursday. Never on the same night.'
  },
  {
    ingredient1: 'retinol',
    ingredient2: 'lactic acid',
    severity: 'high',
    reason: 'Retinol + Lactic Acid (AHA) causes excessive exfoliation. While lactic acid is gentler than glycolic, combining with retinol still risks barrier damage, redness, and peeling.',
    suggestion: 'Alternate nights. Use Lactic Acid 2-3x/week max, Retinol on other nights.'
  },
  {
    ingredient1: 'retinol',
    ingredient2: 'salicylic acid',
    severity: 'high',
    reason: 'Retinol + BHA causes severe over-drying and compromised barrier. Both are strong actives that can irritate skin. Using together amplifies side effects (redness, peeling, burning).',
    suggestion: 'Use BHA in AM and Retinol in PM. Or alternate days — BHA one day, Retinol the next.'
  },
  {
    ingredient1: 'retinol',
    ingredient2: 'benzoyl peroxide',
    severity: 'high',
    reason: 'Benzoyl Peroxide is a powerful oxidizer that chemically destroys retinol, rendering it completely ineffective. Additionally, both are drying and irritating, compounding side effects.',
    suggestion: 'Use BP in AM, Retinol in PM. Or alternate days. Never combine in the same product or routine step.'
  },
  {
    ingredient1: 'benzoyl peroxide',
    ingredient2: 'vitamin c',
    severity: 'medium',
    reason: 'Benzoyl Peroxide oxidizes Vitamin C, making it ineffective. BP generates free radicals (which kill bacteria) that also destroy Vitamin C\'s antioxidant structure.',
    suggestion: 'Use Vitamin C in AM, Benzoyl Peroxide in PM. Or use on alternate days.'
  },
  {
    ingredient1: 'benzoyl peroxide',
    ingredient2: 'salicylic acid',
    severity: 'medium',
    reason: 'Both are drying and potentially irritating. Together they can severely compromise the skin barrier, causing rebound oil production and worse acne.',
    suggestion: 'Use one in AM and one in PM, or alternate days. Monitor for excessive dryness.'
  },
  {
    ingredient1: 'benzoyl peroxide',
    ingredient2: 'glycolic acid',
    severity: 'medium',
    reason: 'Combining BP with AHA causes excessive dryness, peeling, and potential chemical burn. Both lower skin pH and compromise barrier.',
    suggestion: 'Use on alternate days. Never layer directly.'
  },
  {
    ingredient1: 'glycolic acid',
    ingredient2: 'salicylic acid',
    severity: 'medium',
    reason: 'AHA + BHA together is extremely aggressive. Both are chemical exfoliants that remove dead skin — combining them causes over-exfoliation, barrier damage, and increases infection risk.',
    suggestion: 'Don\'t use on the same day. Alternate days or use a professionally formulated AHA-BHA product.'
  },
  {
    ingredient1: 'glycolic acid',
    ingredient2: 'lactic acid',
    severity: 'low',
    reason: 'Using multiple AHAs together causes over-exfoliation. While they work similarly, combining them increases total acid concentration without added benefit.',
    suggestion: 'Choose ONE AHA. Glycolic for stronger results, Lactic for gentler exfoliation.'
  },
  {
    ingredient1: 'vitamin c',
    ingredient2: 'niacinamide',
    severity: 'low',
    reason: 'Previously thought incompatible due to niacin formation at low pH. Modern research shows they are actually compatible and synergistic. Very high concentrations may cause minor flushing in sensitive individuals.',
    suggestion: 'Generally safe to combine. If concerned, use Vitamin C in AM, Niacinamide in PM.'
  },
  {
    ingredient1: 'retinol',
    ingredient2: 'tea tree oil',
    severity: 'low',
    reason: 'Both can be drying and irritating. Tea tree oil\'s potency combined with retinol may increase sensitivity and irritation.',
    suggestion: 'If using both, apply tea tree oil in AM and retinol in PM. Monitor for excessive dryness.'
  },
];

// ── Helper: find ingredient in database ──
export function findIngredient(input: string): string | null {
  const normalized = input.trim().toLowerCase().replace(/\s+/g, ' ');
  // Exact match
  if (ingredientDatabase[normalized]) return normalized;
  // Alternative name match
  for (const [key, data] of Object.entries(ingredientDatabase)) {
    if (data.alternativeNames.some(alt => alt.toLowerCase() === normalized)) return key;
    if (normalized.includes(key) || key.includes(normalized)) return key;
    if (data.alternativeNames.some(alt => normalized.includes(alt.toLowerCase()) || alt.toLowerCase().includes(normalized))) return key;
  }
  return null;
}
